---
kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

# replace <your-demo-name> with your demo name for eg.: financial-news-vector-search
steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com ## keep same for all demos < - aws ecr registry used to store docker image
      repo: industrysolutions/voyage-ai-search
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile
      access_key:
        from_secret: ecr_access_key ## set in drone web ui
      secret_key:
        from_secret: ecr_secret_key ## set in drone web ui
    when:
      event:
        - push

  - name: deploy-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: voyage-ai-search
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/voyage-ai-search"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=multimodal-search.industrysolutions.staging.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token ## set in drone web ui
      values_files: [ "environment/staging.yaml" ]
    when:
      event:
        - push

---
kind: pipeline
type: kubernetes
name: production

trigger:
  branch:
    - main  # or master, depending on your main branch name

steps:
  - name: publish-backend-prod
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/voyage-ai-search-prod
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}-prod
        - prod-latest
      dockerfile: Dockerfile
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: deploy-production
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: voyage-ai-search-prod
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}-prod"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/voyage-ai-search-prod"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=multimodal-search.industrysolutions.prod.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
      values_files: [ "environment/production.yaml" ]
    when:
      event:
        - push
